### PR TITLE
Local notifications

### PR DESCRIPTION
**Pull request by negue**
Added ngCordova (so that more cordova modules can be used easier as service )
& localNotifications with a time setting

### CODE REVIEW

**Comment by negue** [comment]
- Added some more remindMessages thx to @lemoness 
- Merged with latest master branch

**Comment by negue** [comment]
@paglias @crookedneighbor @huaruiwu -  I'd like to merge it in some hours ^^ , any thoughts?

**Comment by paglias** [comment]
@negue I suppose we'll need to test it on a live device, no browser, right?

**Comment by negue** [comment]
Yup, just publish it to a device.

@crookedneighbor can you test it on a iphone build?

**Comment by crookedneighbor** [comment]
@negue I don't have an apple developer subscription right now, but if it's very important, I'll go ahead and purchase one. Been meaning to do it anyway. Just let me know.

If there's a way to test it without (which I've done before using TestFlight, I believe), let me know.

**Comment by negue** [comment]
Oh you need a subscription just to compile and test an app? ... oh boy.. nah not that important. But once the android version is good to go, then @lefnire  could test the ios version :stuck_out_tongue_winking_eye:

**Comment by crookedneighbor** [comment]
@negue Apple is pretty controlling about what it allows on devices. If I decide to purchase the developer license in the near future, I'll let you know.

**Pull request merged**
