### PR TITLE
FirefoxOS support

### LINKED ISSUE #321: FirefoxOS support [$20]
Could somebody build the application and upload it to Firefox Marketplace? And also add note to the footer of HabitRPG website? Thanks!

<bountysource-plugin>
---
There is a **[$20 open bounty](https://www.bountysource.com/issues/7470755-firefoxos-support-20?utm_campaign=plugin&utm_content=tracker%2F85449&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F85449&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by neoascetic**
TODO:
- [x] base functionality
- [x] [upload to marketplace](https://marketplace.firefox.com/app/habitrpg/)
- [ ] make an privileged app
- [ ] fix in-app purchases

### CODE REVIEW

**Comment by crookedneighbor** [comment]
ping @negue and @lefnire

**Comment by negue** [comment]
@neoascetic FirefoxOS only had an issue with the Links?

Did you tried to create a firefoxos package?

**Comment by neoascetic** [comment]
Main issue is with CSP: lodash tries to create function via constructor which is [blocked](https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP) by CSP for privileged apps. Privileged type is required in order to be able to use [browser](https://developer.mozilla.org/en-US/Apps/Build/App_permissions#browser) feature. I don't know if this really needed because I've built package without this permission (i. e. unprivileged simple web app, see [types of packages](https://developer.mozilla.org/en-US/Marketplace/Options/Packaged_apps#Types_of_packaged_apps)) and it works in both emulator and my phone (one issue though - images are blinking on phone, but I think this is different issue).

If we are OK with unprivileged package (which still may be pushed to the Marketplace), need somehow  restrict ionic to set type in the manifest file while running `ionic build`. I haven't worked with Angular, Ionic, Cordova and company until this moment, I just want to see HabitRPG on my phone! :)

There is also issue with icons - they are not going to be copied to the package on build. As I understood from `res/icons.sh`, this action should be done manually. Am I right?

Thanks.

**Comment by neoascetic** [comment]
CSP issues caused by Angular was fixed with adding `ng-csp` attribute to the body, but lodash, obviously, doesn't care about it.

**Comment by neoascetic** [comment]
As I think, images blinks due to rendering engine - same issue when I open mobile site with regular browser. I am using Firefox OS 1.3 and I hope this will be fixed with update, so for now this issue may be ignored: at least, I am able to track my progress.

**Comment by neoascetic** [comment]
I think now this may be merged. It is hardly possible that this may break something. There are still some issues, but for now I am happy with manually built package on my phone. I could upload it to Firefox Marketplace, but I think this should be done by HabitRPG team. Regardless some issues, it is better than nothing and I think Firefox OS users would be happy. It also would be great to have link to the app on the main website.

Thanks!

**Comment by neoascetic** [comment]
You may try it yourself with Firefox and its WebIDE.

**Comment by negue** [comment]
I'll try it tmrw with the FirefoxOS Emulator, if its okay with you.

`images blinks due to rendering engine` this issues seems to exists on many mobile browsers ^^

Will post once I saw how and what works on firefoxos

**Comment by neoascetic** [comment]
@negue any news?

**Comment by negue** [comment]
Sorry it took me that long :/

I tried it now, but firefox won't let me install any simulator, just "Install Failed" and thats it.

Will post again once I have the simulator running

**Comment by neoascetic** [comment]
@negue That's bad. Any other way to approve this PR?

**Comment by negue** [comment]
Today I'll look into it again, on a different environment

**Comment by lefnire** [comment]
Actually a bit torn on this. I don't think we'd have the resources to support a FirefoxOS app (even though you've done the leg work here, we wouldn't necessarily have anyone to stick with it going forward for bugs / new features / etc). I'd say, maybe if you're willing to deploy & support the app @neoascetic, then you have our blessing - but I wanna get an ok from @lemoness & @veeeeeee first

**Comment by veeeeeee** [comment]
I'm fine with it as an unofficial third party app. @lefnire is correct in that we don't quite have the resources to do a lot of support on it (much like the situation with Windows) but if @neoascetic would like to take point on a third party solution, that's ok by me.

**Comment by lemoness** [comment]
I agree that it makes more sense as a third-party app!

**Comment by neoascetic** [comment]
I got it. If you okay with it, I would like to keep this PR open and continue to push changes.

**Comment by crookedneighbor** [comment]
@neoascetic Closing this now, but if you did finish it, please add a link in the wiki!

**Comment by neoascetic** [comment]
May I have contributor badge? :)

**Pull request closed without merging**
