### PR TITLE
Only copy files that are needed on the mobile

### PR DESCRIPTION
**Pull request by negue**
./www Size:

Before: 31,4 MB
Now: 8,93 MB

### CODE REVIEW

**Comment by lefnire** [comment]
holy god, that's a difference! will look into for next deploy, thanks man

**Comment by negue** [comment]
@lefnire Should I close this pullrequest? Or update it to the latest commit?

**Comment by crookedneighbor** [comment]
Pinging @negue and @lefnire

**Comment by lefnire** [comment]
let's update it to the latest commit

**Comment by negue** [comment]
Closing this because of #361

**Pull request closed without merging**
