### PR TITLE
Fixes iOS statusbar issues

### PR DESCRIPTION
**Pull request by PJay-**
Ignore H..., if you switch screens it changes to the full text

Current behaviour:

screen shot 2015-03-12 at 23 15 33
screen shot 2015-03-12 at 23 15 38

Fixed behaviour:

screen shot 2015-03-12 at 23 16 13
screen shot 2015-03-12 at 23 16 17

### CODE REVIEW

**Comment by lefnire** [comment]
duuude.. rad. Hope to test out locally in a day or two, if I lag ping me again and I'll just merge :)

**Comment by PJay-** [comment]
@lefnire will do!

**Comment by PJay-** [comment]
ping @lefnire

**Comment by lefnire** [comment]
contrib.lvl++, thanks again!

**Comment by PJay-** [comment]
Cool np!

**Pull request merged**
